import { colors } from "./colors";
import { portfolio } from "./portfolio";
import { spacing } from "./spacing";
import { typography } from "./typography";

export { colors, portfolio, spacing, typography };

// 把 token 同步成全局 CSS 变量，这样组件样式和预览页面都能共用同一份设计值。
export const rootCssVariables = {
  "--ds-color-canvas": colors.canvas,
  "--ds-color-surface": colors.surface,
  "--ds-color-surface-soft": colors.surfaceSoft,
  "--ds-color-surface-muted": colors.surfaceMuted,
  "--ds-color-ink": colors.ink,
  "--ds-color-ink-soft": colors.inkSoft,
  "--ds-color-text": colors.text,
  "--ds-color-text-support": colors.textSupport,
  "--ds-color-text-muted": colors.textMuted,
  "--ds-color-text-subtle": colors.textSubtle,
  "--ds-color-border": colors.border,
  "--ds-color-border-soft": colors.borderSoft,
  "--ds-color-border-muted": colors.borderMuted,
  "--ds-color-accent-sky": colors.accentSky,
  "--ds-color-accent-blush": colors.accentBlush,
  "--ds-color-accent-sand": colors.accentSand,
  "--ds-space-2xs": spacing["2xs"],
  "--ds-space-xs": spacing.xs,
  "--ds-space-sm": spacing.sm,
  "--ds-space-md": spacing.md,
  "--ds-space-lg": spacing.lg,
  "--ds-space-xl": spacing.xl,
  "--ds-space-2xl": spacing["2xl"],
  "--ds-space-3xl": spacing["3xl"],
  "--ds-space-section": spacing.section,
  "--ds-space-hero": spacing.hero,
  "--ds-font-display": typography.families.display,
  "--ds-font-ui": typography.families.ui,
  "--ds-font-body": typography.families.body,
  "--ds-type-display-size": typography.scales.display.size,
  "--ds-type-display-line": typography.scales.display.lineHeight,
  "--ds-type-display-weight": typography.scales.display.weight,
  "--ds-type-heading-lg-size": typography.scales.headingLg.size,
  "--ds-type-heading-lg-line": typography.scales.headingLg.lineHeight,
  "--ds-type-heading-lg-weight": typography.scales.headingLg.weight,
  "--ds-type-heading-md-size": typography.scales.headingMd.size,
  "--ds-type-heading-md-line": typography.scales.headingMd.lineHeight,
  "--ds-type-heading-md-weight": typography.scales.headingMd.weight,
  "--ds-type-heading-sm-size": typography.scales.headingSm.size,
  "--ds-type-heading-sm-line": typography.scales.headingSm.lineHeight,
  "--ds-type-heading-sm-weight": typography.scales.headingSm.weight,
  "--ds-type-body-lg-size": typography.scales.bodyLg.size,
  "--ds-type-body-lg-line": typography.scales.bodyLg.lineHeight,
  "--ds-type-body-lg-weight": typography.scales.bodyLg.weight,
  "--ds-type-body-sm-size": typography.scales.bodySm.size,
  "--ds-type-body-sm-line": typography.scales.bodySm.lineHeight,
  "--ds-type-body-sm-weight": typography.scales.bodySm.weight,
  "--ds-type-label-size": typography.scales.label.size,
  "--ds-type-label-line": typography.scales.label.lineHeight,
  "--ds-type-label-weight": typography.scales.label.weight,
  "--ds-type-overline-size": typography.scales.overline.size,
  "--ds-type-overline-line": typography.scales.overline.lineHeight,
  "--ds-type-overline-weight": typography.scales.overline.weight,
  "--ds-radius-sm": "0.75rem",
  "--ds-radius-md": "1rem",
  "--ds-radius-lg": "1.5rem",
  "--ds-radius-xl": "1.75rem",
  "--ds-radius-pill": "999px",
  "--ds-shadow-soft": "0 18px 40px rgba(20, 24, 27, 0.06)",
  "--ds-shadow-edge": "inset 0 0 0 1px rgba(227, 229, 232, 1)",
};
