// 这份 token 专门服务作品集页面，不直接替换现有通用设计系统。
// 先把方向稳定下来，后续页面可以按需接入，而不是一次性全局替换。
export const portfolio = Object.freeze({
  colors: Object.freeze({
    canvas: "#fcfbf8",
    surface: "#ffffff",
    surfaceWarm: "#f0ede8",
    textTitle: "#2d2f30",
    textBody: "#4a4d4e",
    textMuted: "#7a7e80",
    borderLight: "#ece9e4",
    borderStrong: "#dcd9d1",
    accentBrand: "#b36a5e",
  }),
  typography: Object.freeze({
    families: Object.freeze({
      // 一级标题统一切到项目内托管的“方正清刻本悦宋”，避免继续依赖本机字体。
      title:
        'var(--font-fz-qingke-benyuesong), "Songti SC", "STSong", serif',
      body:
        'var(--font-satoshi), "Inter", "Noto Sans SC", "Noto Sans JP", sans-serif',
      label:
        'var(--font-satoshi), "Inter", "Noto Sans SC", "Noto Sans JP", sans-serif',
      mono: 'var(--font-ibm-plex-mono, "IBM Plex Mono", monospace)',
    }),
    scales: Object.freeze({
      hero: Object.freeze({
        size: "3rem",
        lineHeight: "3rem",
        weight: 400,
        letterSpacing: "0",
      }),
      sectionTitle: Object.freeze({
        size: "1.5rem",
        lineHeight: "normal",
        weight: 400,
        letterSpacing: "0",
      }),
      body: Object.freeze({
        size: "1rem",
        lineHeight: "1.5rem",
        weight: 400,
        letterSpacing: "-0.011rem",
      }),
      label: Object.freeze({
        size: "1rem",
        lineHeight: "1.5rem",
        weight: 500,
        letterSpacing: "-0.011rem",
      }),
      bodySm: Object.freeze({
        size: "0.875rem",
        lineHeight: "1.25rem",
        weight: 400,
        letterSpacing: "-0.00525rem",
      }),
      caption: Object.freeze({
        size: "0.75rem",
        lineHeight: "1rem",
        weight: 400,
        letterSpacing: "0",
      }),
    }),
  }),
  spacing: Object.freeze({
    "2xs": "0.375rem",
    xs: "0.75rem",
    sm: "1.5rem",
    md: "3rem",
    lg: "6rem",
    sectionPaddingY: "8.25rem",
  }),
  radius: Object.freeze({
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    hero: "4rem",
  }),
  shadows: Object.freeze({
    card: "0 16px 32px -12px rgba(14, 18, 27, 0.1)",
  }),
  layout: Object.freeze({
    pageGutter: "34rem",
    contentWidth: "52rem",
    heroWidth: "90rem",
  }),
  semantics: Object.freeze({
    sectionBackground: "var(--portfolio-color-surface, #ffffff)",
    mediaFrameBackground: "var(--portfolio-color-surface-warm, #f0ede8)",
    mediaFrameBorder: "var(--portfolio-color-border-light, #ece9e4)",
    eyebrowColor: "var(--portfolio-color-accent-brand, #b36a5e)",
    captionColor: "var(--portfolio-color-text-muted, #7a7e80)",
    bodyColor: "var(--portfolio-color-text-body, #4a4d4e)",
    titleColor: "var(--portfolio-color-text-title, #2d2f30)",
  }),
  work: Object.freeze({
    borderWidth: "1px",
    innerRadiusOffset: "1px",
    pageHeader: Object.freeze({
      titleSize: "2rem",
      titleLetterSpacing: "-0.038125rem",
      titleLineHeight: "1.2",
      mobileTitleSize: "1.75rem",
    }),
    tabs: Object.freeze({
      minHeight: "2.375rem",
      paddingBlock: "0.5625rem",
      paddingInline: "0.8125rem",
      radius: "1rem",
      focusOutlineWidth: "2px",
      focusOutlineOffset: "2px",
    }),
    projectCard: Object.freeze({
      padding: "1.5625rem",
      previewRadius: "0.75rem",
      previewOverlayRadius: "0.25rem",
      titleSize: "1.5rem",
      titleLineHeight: "1.5",
      summaryLineHeight: "1.375rem",
      transitionDuration: "180ms",
      hoverTranslateY: "-1px",
      mobilePadding: "1rem",
      mobileRadius: "1.25rem",
      mobileTitleSize: "1.25rem",
      mobileTitleLineHeight: "1.35",
      mobileSummarySize: "0.9375rem",
      mobileSummaryLineHeight: "1.5rem",
    }),
    tag: Object.freeze({
      borderWidth: "0.5px",
      radius: "0.375rem",
      minHeight: "1.5rem",
      paddingBlock: "0.25rem",
      paddingInline: "0.5rem",
      lineHeight: "1rem",
    }),
    exploration: Object.freeze({
      cardFeatureMinHeight: "26rem",
      cardCompactMinHeight: "22.375rem",
      cardPaddingFeatureBlock: "8.3125rem",
      cardPaddingFeatureInline: "1.5625rem",
      cardPaddingCompactBlock: "3.0625rem",
      cardPaddingCompactInline: "1.5625rem",
      cardTallMinHeight: "28.1875rem",
      cardTallImageMinHeight: "28.0625rem",
      earningsHeight: "9.375rem",
      earningsRadius: "2.25rem",
      earningsVisualMaxWidth: "28.5rem",
      earningsOrbWidth: "40.1875rem",
      earningsOrbAspectRatio: "643 / 270",
      earningsOrbInsetTop: "-11.333rem",
      earningsOrbInsetLeft: "-11.3125rem",
      earningsGlowWidth: "40.1875rem",
      earningsGlowHeight: "16.875rem",
      earningsGlowBlur: "2.75rem",
      earningsGlowInsetTop: "-3.625rem",
      earningsGlowInsetLeft: "-12.25rem",
      earningsContentMaxWidth: "23.3125rem",
      earningsContentSideInset: "5rem",
      earningsHeaderGap: "0.75rem",
      earningsLabelSize: "1.25rem",
      earningsLabelLineHeight: "1.8",
      earningsAmountSize: "2.5rem",
      deviceMaxWidth: "28.5rem",
      cloudFrameSize: "16.25rem",
      cloudAssetInsetTop: "-7.5%",
      cloudAssetInsetRight: "-25.5%",
      cloudAssetInsetBottom: "-51%",
      cloudAssetInsetLeft: "-25.5%",
      listCompositionHeight: "15.5595rem",
      listSize: "16.25rem",
      listTopShadowHeight: "13.284375rem",
      listTopShadowInsetTop: "2.26875rem",
      listTopShadowAssetInsetTop: "-14.23%",
      listTopShadowAssetInsetRight: "-19.41%",
      listTopShadowAssetInsetBottom: "-32.67%",
      listTopShadowAssetInsetLeft: "-19.41%",
      listBottomShadowHeight: "8.7045rem",
      listBottomShadowInsetTop: "6.855rem",
      listBottomShadowWidth: "16.2253125rem",
      listBottomShadowAssetInsetTop: "-22.66%",
      listBottomShadowAssetInsetRight: "-19.45%",
      listBottomShadowAssetInsetBottom: "-49.86%",
      listBottomShadowAssetInsetLeft: "-19.45%",
      listPhoneWidth: "10.8990625rem",
      listPhoneHeight: "14.1046875rem",
      listPhoneInsetLeft: "2.663125rem",
      listPhoneRadius: "1.5386875rem",
      listPhoneSurfaceHeight: "13.8088125rem",
      listPhoneSurfaceInsetLeft: "-0.024375rem",
      listItemsInsetLeft: "1.9875rem",
      listItemsInsetTop: "2.564375rem",
      listItemsWidth: "6.924125rem",
      listItemsGap: "0.769375rem",
      listLineHeight: "0.7890625rem",
      listLineRadius: "6.347125rem",
      listButtonWidth: "4.0933125rem",
      ticketMaxWidth: "31.25rem",
      ticketAspectRatio: "500 / 314",
      immersiveAspectRatio: "2880 / 1786",
      blurScale: "1.24",
      mobileFeaturePaddingBlock: "3rem",
      mobileFeaturePaddingInline: "1rem",
      mobileCompactPaddingBlock: "1.5rem",
      mobileCompactPaddingInline: "1rem",
      mobileTallMinHeight: "20rem",
      mobileEarningsHeight: "8.25rem",
      mobileEarningsRadius: "1.75rem",
      mobileEarningsContentSideInset: "2.5rem",
      mobileEarningsLabelSize: "0.9375rem",
      mobileEarningsAmountSize: "2rem",
      mobileListSize: "12rem",
      mobileListScale: "0.7385",
      earningsSurface: "#ff551a",
      earningsInsetShadow: "inset -8px 1px 13.5px 0 #ff541b",
      earningsGlowColor: "rgba(43, 43, 43, 0.96)",
      earningsHighlight:
        "linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.02) 56%, rgba(255, 255, 255, 0.16) 100%)",
      earningsLabelColor: "#727070",
      listGradient:
        "linear-gradient(145.87deg, #ff9900 0%, #ff004d 96.43%)",
    }),
    sideProject: Object.freeze({
      padding: "1.5625rem",
      titleSize: "1.125rem",
      titleLineHeight: "1.5556",
      bodyLineHeight: "1.4286",
      transitionDuration: "180ms",
      hoverTranslateY: "-1px",
      hoverPathShiftX: "0.25rem",
      focusOutlineWidth: "2px",
      focusOutlineOffset: "2px",
      mobilePadding: "1rem",
      mobileGap: "0.75rem",
    }),
  }),
});
